<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>Dialog</name>
    <message>
        <location filename="../../ui/example_dialog.ui" line="14"/>
        <source>example_dialog</source>
        <translation type="unfinished">Esimerkki dialogi</translation>
    </message>
    <message>
        <location filename="../../ui/example_dialog.ui" line="20"/>
        <source>addLayer</source>
        <translation type="unfinished">Lisää karttataso</translation>
    </message>
    <message>
        <location filename="../../ui/example_dialog.ui" line="27"/>
        <source>removeLayer</source>
        <translation type="unfinished">Poista karttataso</translation>
    </message>
</context>
<context>
    <name>example</name>
    <message>
        <location filename="../../ui/example_dialog.py" line="37"/>
        <source>addRasterLayer</source>
        <translation type="unfinished">Karttataso lisätty</translation>
    </message>
</context>
<context>
    <name>exceptions</name>
    <message>
        <location filename="../../exceptions.py" line="20"/>
        <source>baseException</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../exceptions.py" line="49"/>
        <source>genericError</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../exceptions.py" line="53"/>
        <source>unkownError</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../exceptions.py" line="57"/>
        <source>networkError</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../exceptions.py" line="80"/>
        <source>configException</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
